#!/bin/sh
set -e

# Install icon caches for the included icon themes
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if which update-icon-caches >/dev/null 2>&1 ; then
		update-icon-caches /usr/share/icons/elementary-xfce /usr/share/icons/elementary-xfce-dark /usr/share/icons/elementary-xfce-darker /usr/share/icons/elementary-xfce-darkest
	fi
fi

#DEBHELPER#
exit 0
